freenom:
  username: 1543267684@qq.com
  password: hy1998HY...
  email:
    subject: Im Robot
    from: 1492445352@qq.com
    to: coolkidhay@foxmail.com

spring:
  mail:
    host: smtp.qq.com # 发件服务器
    username: 1492445352@qq.com # 账号
    password: jbfipslmiicabadd # 密码（163需要授权第三方登录密码，请查看设置-客户端授权码密码开通）
    port: 465
    protocol: smtp
    default-encoding: utf-8
    # 下面这些配置大家不用深究，主要用于配置ssl
    properties:
      mail:
        imap:
          ssl:
            socketFactory:
              fallback: false
        smtp:
          auth: true
          ssl:
            enable: true
            socketFactory:
              class: com.fintech.modules.base.util.mail.MailSSLSocketFactory
          starttls:
            enable: true
            required: true
      test-connection: false
  mvc:
    static-path-pattern: /static/**
server:
  port: 8001