# Tomcat
server:
  port: 12701

# Spring
spring:
  application:
    # 应用名称
    name: Freenom
  profiles:
    # 环境配置
    active: dev
nacos:
  config:
    group: myProject
    data-id: ${spring.application.name}-${spring.profiles.active}.yml
    server-addr: 127.0.0.1:8848
    type: yaml
    context-path: /nacos
    bootstrap:
      enable: false
      log-enable: true
    #    namespace: gz
    auto-refresh: true
  discovery:
    server-addr: 127.0.0.1:8848
    auto-register: true
    register:
      service-name: ${spring.application.name}-${spring.profiles.active}
      ip: 127.0.0.1
      port: ${server.port}
      metadata: {group: "myProject",context-path: "/nacos"}
    context-path: /nacos
#    namespace: gz